FROM registry.altlinux.org/alt/alt:p11

# set version label
ARG UID=1000
ARG GID=1000

ENV UNAME=api
ENV APP_HOME=/home/$UNAME/app

RUN \
    # fix Apt source lists
    rm -f /etc/apt/sources.list.d/*.list \
    && echo "rpm [p11] http://ftp.altlinux.org/pub/distributions/ALTLinux p11/branch/x86_64 classic" > /etc/apt/sources.list.d/alt.list \
    && echo "rpm [p11] http://ftp.altlinux.org/pub/distributions/ALTLinux p11/branch/noarch classic" >> /etc/apt/sources.list.d/alt.list \
    # installing packages
    && apt-get update \
    && yes | apt-get dist-upgrade \
    && yes | apt-get install \
        python3-module-flask \
        python3-module-flask-restx \
        python3-module-mmh3 \
        python3-module-clickhouse-driver \
        python3-module-gunicorn \
        python3-module-packaging \
        python3-module-ldap \
        python3-module-jwt \
        python3-module-redis-py \
        python3-module-flask-cors \
        python3-module-requests \
        python3-module-orjson \
        tzdata \
        python3-module-pytest \
        python3-module-pytest-flask \
        openldap-servers \
        openldap-clients \
    # install altrepodb_libs module from tasks
        apt-repo \
    && apt-repo add 360089 \
    && apt-get update \
    && yes | apt-get install python3-module-altrepodb_libs \
    # clean-up Apt caches
    && rm -f /var/cache/apt/archives/*.rpm \
        /var/cache/apt/*.bin \
        /var/lib/apt/lists/*.* \
    # create user and directories
    && groupadd -g $GID -o $UNAME \
    && useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME \
    && mkdir -p /config && mkdir -p /log \
    && chown -R $UID:$GID /config \
    && chown -R $UID:$GID /log \
    && mkdir $APP_HOME

WORKDIR $APP_HOME

COPY . $APP_HOME

RUN chown -R $UID:$GID $APP_HOME

USER $UNAME

RUN touch $APP_HOME/tests/api.conf
